### ISSUE TITLE
Tweet IDs

### ISSUE THREAD

**Issue by FuriouslyCurious** [ignacio/LuaOAuth#14]
Hi Ignacio,

I used your examples to build a Twitter bot: most of the functionality works great but I am having trouble parsing Tweet IDs from search API call.

Search API call returns 18 digit integer as Tweet ID.  When I decode the JSON output, ID is truncated to 14 Digit float and no longer usable for liking / favoriting.  

Can you please share suggestions on how you would handle this?  Will be great if you can show code to handle Twitter Search API results properly.

Thanks!

**Comment by ignacio** [comment]
Take a look at this [example on searching](https://dev.twitter.com/rest/reference/get/search/tweets) in Twitter's docs. Instead of using _id_ you just use _id_str_. That also applies to many other numeric attributes (like user ids). They also have a string representation that you can use.

Hope this helps.

**Comment by FuriouslyCurious** [comment]
Thank you Ignacio - I am looking into it now.
